### REGISTER

POST http://localhost:3000/auth/register
Content-Type: application/json

{
    "nom": "test3",
    "email": "test3@test.com",
    "password": "123456"
}



### LOGIN

# @name login
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "test3@test.com",
    "password": "123456"
}

###

# @name login
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "admin1@test.com",
    "password": "123456"
}

###

### TEST ROUTE PROTÉGÉE

GET http://localhost:3000/auth/me
Authorization: Bearer {{login.response.body.token}}


###

###tEST ROLE ADMIN

GET http://localhost:3000/auth/admin-test
Authorization:  Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsInJvbGUiOiJVVElMSVNBVEVVUiIsImlhdCI6MTc4NjcyNzQyNSwiZXhwIjoxNzg2NzMxMDI1fQ.qMTjNZeZag2ljMSsHR8mwWoQ3PPcMZsJCwXPlRxtP5M

### TEST LOGOUT

POST http://localhost:3000/auth/logout
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsInJvbGUiOiJVVElMSVNBVEVVUiIsImlhdCI6MTc4NjcyODk4NSwiZXhwIjoxNzg2NzMyNTg1fQ.XySww8ggK4MWq-HErlV3X5j73wU8wPQ7xasC-fQzCRc

### UPDATE PRIVACY

PATCH http://localhost:3000/users/privacy
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsInJvbGUiOiJVVElMSVNBVEVVUiIsImlhdCI6MTc4NjczNDA1MSwiZXhwIjoxNzg2NzM3NjUxfQ.chISj4r2iEWpXPjdtPpdCC2OidaDz1YTgBEYmBV2wXU
Content-Type: application/json

{
    "parametresVisibilite": "PUBLIC",
    "parametresDeContact": "MEMBRES_DE_MES_GROUPES"
}

### SEND MESSAGE

POST http://localhost:3000/messages
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsInJvbGUiOiJVVElMSVNBVEVVUiIsImlhdCI6MTc4NjczNDQ5MSwiZXhwIjoxNzg2NzM4MDkxfQ.zitHPfD8YrJDCkE1eCtUBoJUTrijFbQ2hCTZ2NJwB_g
Content-Type: application/json

{
    "recipiantId": 3,
    "contenu": "Bonjour depuis MindHarbor !"
}




### GET toutes journal entries
GET http://localhost:3000/journal
Authorization: Bearer {{login.response.body.token}}

### GET journal entry by date
GET http://localhost:3000/journal/2026-08-15
Authorization: Bearer {{login.response.body.token}}

### CREATE journal entry
POST http://localhost:3000/journal
Authorization: Bearer {{login.response.body.token}}
Content-Type: application/json

{
    "humeurGenerale": 5,
    "niveauEnergie": 5,
    "qualiteDuSommeil": 5,
    "niveauAnxiete": 5,
    "evenementMarquants": "Bonne journée au travail",
    "gratitude": "Reconnaissant pour ma famille",
    "activityId": []
}

### UPDATE journal entry by date
PATCH http://localhost:3000/journal/2026-08-15
Authorization: Bearer {{login.response.body.token}}
Content-Type: application/json

{
    "humeurGenerale": 1,
    "niveauEnergie": 1,
    "qualiteDuSommeil": 1,
    "niveauAnxiete": 1,
    "evenementMarquants": "Bonne journée au travail",
    "gratitude": "Reconnaissant pour ma famille",
    "activityId": []
}

### GET journal stats


### GET journal insights



###################################

### toutes les actibites
GET http://localhost:3000/activities

### (resource) rechercher par titre
GET http://localhost:3000/resources?titre=Comprendre l'anxiété

### (resource) recherche par categorie
GET http://localhost:3000/resources?categorie=ANXIETE

### (resource) recherche par type
GET http://localhost:3000/resources?type=ARTICLE

### (resource) RECHERche par niveau
GET http://localhost:3000/resources?niveau=DEBUTANT

### (resource) tous les resources
GET http://localhost:3000/resources?page=1&limit=5


### (ADMIN) cree resource 1
POST http://localhost:3000/resources
Authorization: Bearer {{login.response.body.token}}
Content-Type: application/json

{
  "titre": "Comprendre l'anxiété",
  "contenu": "Guide complet sur l'anxiété.",
  "categorie": "ANXIETE",
  "type": "ARTICLE",
  "duree": 15,
  "niveau": "DEBUTANT"
}

### (ADMIN) cree resource 2 
POST http://localhost:3000/resources
Authorization: Bearer {{login.response.body.token}}
Content-Type: application/json

{
  "titre": "Améliorer son sommeil",
  "contenu": "Quelques conseils pour améliorer la qualité du sommeil.",
  "categorie": "SOMMEIL",
  "type": "ARTICLE",
  "duree": 15,
  "niveau": "DEBUTANT"
}


### chercher une resource par id 
GET http://localhost:3000/resources/cmsvirz1t0000dovs1zagpp48


### ajout aux favoris
POST http://localhost:3000/resources/cmsvirz1t0000dovs1zagpp48/favorite
Authorization: Bearer {{login.response.body.token}}

### tous les favoris
GET http://localhost:3000/me/favorite
Authorization: Bearer {{login.response.body.token}}

### delete favoris
DELETE http://localhost:3000/resources/cmsvirz1t0000dovs1zagpp48/favorite
Authorization: Bearer {{login.response.body.token}}

### suggestions 
GET http://localhost:3000/me/suggestions
Authorization: Bearer {{login.response.body.token}}




##########################

### liste des groups
GET http://localhost:3000/groups


### recherche dun groupe
GET http://localhost:3000/groups?search=anxiete

### creee group
POST http://localhost:3000/groups
Authorization: Bearer {{login.response.body.token}}
Content-Type: application/json

{
    "nom": "Gestion de l'anxiété",
    "theme": "ANXIETE",
    "description": "Groupe d'entraide pour les personnes anxieuses",
    "regles": "Respect et bienveillance",
    "visibilite": "PUBLIC"
}


### chercher un group par id
GET http://localhost:3000/groups/cmsvmvdx1000008vsnekpto2h



### demander de joindre un group
POST http://localhost:3000/groups/cmsvmvdx1000008vsnekpto2h/join
Authorization: Bearer {{login.response.body.token}}



### (MODERATEUIR) voire les demandes
GET http://localhost:3000/groups/cmsvmvdx1000008vsnekpto2h/requests
Authorization: Bearer {{login.response.body.token}}


### (MODERATEUR) accepter une demande
PATCH http://localhost:3000/groups/cmsvmvdx1000008vsnekpto2h/requests/cmsvnkz1800031ovsldxzwwav
Authorization: Bearer {{login.response.body.token}}
Content-Type: application/json

{
    "statut": "ACCEPTEE"
}


### voir puvlications du groupe
GET http://localhost:3000/groups/cmsvmvdx1000008vsnekpto2h/posts
Authorization: Bearer {{login.response.body.token}}

### cree publication
POST http://localhost:3000/groups/cmsvmvdx1000008vsnekpto2h/posts
Authorization: Bearer {{login.response.body.token}}
Content-Type: application/json

{
    "contenu": "Bonjour tout le monde, je suis nouveau dans ce groupe."
}

### supprimer publication (PPAS ENCORE FAIT)
DELETE http://localhost:3000/posts/cmsvnf9s400001ovsmb5akf18
Authorization: Bearer {{login.response.body.token}}

### post commentair
POST http://localhost:3000/posts/cmsvnf9s400001ovsmb5akf18/comments
Authorization: Bearer {{login.response.body.token}}
Content-Type: application/json

{
    "contenu": "Merci pour ton partage."
}