### REGISTER

POST http://localhost:3000/auth/register
Content-Type: application/json

{
    "nom": "test3",
    "email": "test3@test.com",
    "password": "123456"
}



### LOGIN

# @name login
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "test3@test.com",
    "password": "123456"
}

###

### TEST ROUTE PROTÉGÉE

GET http://localhost:3000/auth/me
Authorization: Bearer {{login.response.body.token}}


###

###tEST ROLE ADMIN

GET http://localhost:3000/auth/admin-test
Authorization:  Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsInJvbGUiOiJVVElMSVNBVEVVUiIsImlhdCI6MTc4NjcyNzQyNSwiZXhwIjoxNzg2NzMxMDI1fQ.qMTjNZeZag2ljMSsHR8mwWoQ3PPcMZsJCwXPlRxtP5M

### TEST LOGOUT

POST http://localhost:3000/auth/logout
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsInJvbGUiOiJVVElMSVNBVEVVUiIsImlhdCI6MTc4NjcyODk4NSwiZXhwIjoxNzg2NzMyNTg1fQ.XySww8ggK4MWq-HErlV3X5j73wU8wPQ7xasC-fQzCRc

### UPDATE PRIVACY

PATCH http://localhost:3000/users/privacy
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsInJvbGUiOiJVVElMSVNBVEVVUiIsImlhdCI6MTc4NjczNDA1MSwiZXhwIjoxNzg2NzM3NjUxfQ.chISj4r2iEWpXPjdtPpdCC2OidaDz1YTgBEYmBV2wXU
Content-Type: application/json

{
    "parametresVisibilite": "PUBLIC",
    "parametresDeContact": "MEMBRES_DE_MES_GROUPES"
}

### SEND MESSAGE

POST http://localhost:3000/messages
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsInJvbGUiOiJVVElMSVNBVEVVUiIsImlhdCI6MTc4NjczNDQ5MSwiZXhwIjoxNzg2NzM4MDkxfQ.zitHPfD8YrJDCkE1eCtUBoJUTrijFbQ2hCTZ2NJwB_g
Content-Type: application/json

{
    "recipiantId": 3,
    "contenu": "Bonjour depuis MindHarbor !"
}




### GET toutes journal entries
GET http://localhost:3000/journal
Authorization: Bearer {{login.response.body.token}}

### GET journal entry by date
GET http://localhost:3000/journal/2026-08-15
Authorization: Bearer {{login.response.body.token}}

### CREATE journal entry
POST http://localhost:3000/journal
Authorization: Bearer {{login.response.body.token}}
Content-Type: application/json

{
    "humeurGenerale": 5,
    "niveauEnergie": 5,
    "qualiteDuSommeil": 5,
    "niveauAnxiete": 5,
    "evenementMarquants": "Bonne journée au travail",
    "gratitude": "Reconnaissant pour ma famille",
    "activityId": []
}

### UPDATE journal entry by date
PATCH http://localhost:3000/journal/2026-08-15
Authorization: Bearer {{login.response.body.token}}
Content-Type: application/json

{
    "humeurGenerale": 1,
    "niveauEnergie": 1,
    "qualiteDuSommeil": 1,
    "niveauAnxiete": 1,
    "evenementMarquants": "Bonne journée au travail",
    "gratitude": "Reconnaissant pour ma famille",
    "activityId": []
}

### GET journal stats


### GET journal insights
